const Router = require('koa-router')
const router = new Router
const article = require('./artice/index')
const comment = require('./comment/index')
const login = require('./login/index')
const userMessage = require('./userMessage/index')
const friendLink = require('./friendLink/index')
const project = require('./project/index')
router.use(article)
  .use(comment)
  .use(login)
  .use(userMessage)
  .use(friendLink)
  .use(project)

module.exports = router.routes()